"""Build the two static case-study pages. Run from any directory with Python 3."""
from pathlib import Path
from html import escape
from hashlib import sha256
import re

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / 'public' if (ROOT / 'public/index.html').is_file() else ROOT

def asset_url(path):
    version = sha256((PUBLIC / path).read_bytes()).hexdigest()[:12]
    return f'{path}?v={version}'

def page(title, description, body):
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f3f7ff"><meta name="description" content="{escape(description, quote=True)}"><title>{escape(title)} · Weiqi Wang</title><link rel="icon" href="../{asset_url('assets/favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="../assets/fonts.css"><link rel="stylesheet" href="../{asset_url('styles.css')}"><script src="../site.js" defer></script></head>
<body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container nav-row"><a class="wordmark" href="../" aria-label="Weiqi Wang, home"><span class="monogram" aria-hidden="true">w<span>.</span></span><span>Weiqi Wang<span class="wordmark-sub">ROBOTICS ENGINEER</span></span></a><nav aria-label="Main navigation"><a href="../#about">About</a><a href="../#work">Work</a><a href="../#publications">Publications</a><a href="../#contact">Contact</a></nav><a class="nav-resume" href="../assets/Weiqi-Wang-Resume.pdf">Resume ↗</a></div></header>
<main id="main">{body}</main><footer class="site-footer container"><span>© <span data-year>2026</span> Weiqi (Rocky) Wang</span><span>Learning · Planning · Control</span><a href="#main">Back to top ↑</a></footer></body></html>'''

SUN = '''
<div class="container"><header class="case-header"><a class="back-link" href="../#work">← Back to selected work</a><p class="eyebrow">ROBOT LEARNING / UCLA / 2026</p><h1>SUN: Agentic Robot Policy Learning<br><span>with Persistent Task Programs</span></h1><p class="case-lead">The Kuafu harness connects language and object videos to multi-stage robot manipulation, combining model predictive control, imitation learning, reinforcement learning, and sim-to-real deployment of visual policies.</p><div class="case-meta"><span>Co-first author</span><span>Under review · 2026</span><span>Franka FR3 + Kinova Gen3</span></div><div class="case-links"><a class="button primary" href="https://kuafu-robo.github.io/" target="_blank" rel="noopener noreferrer">Project website ↗</a><a class="text-link" href="#project-video">Watch the full demo ↓</a></div></header>
<figure class="case-cover"><img src="../assets/chase_sun.png" width="2252" height="1567" alt="SUN Programs connect MPC verification, residual reinforcement learning, and six physical robot tasks"><figcaption>Original project figure: task verification, learning, and zero-shot transfer to physical robots.</figcaption></figure>
<section id="project-video" class="full-project-demo" aria-labelledby="full-video-title"><div class="section-heading"><div><p class="eyebrow">FULL PROJECT VIDEO / 2:11</p><h2 id="full-video-title">SUN / Kuafu in action.</h2></div><a class="text-link" href="https://kuafu-robo.github.io/#video" target="_blank" rel="noopener noreferrer">Open on project website ↗</a></div><video controls controlslist="nodownload" muted playsinline preload="none" poster="../assets/sun-project-poster.jpg" aria-label="Complete SUN and Kuafu project demonstration" aria-describedby="full-video-caption"><source src="../assets/sun-project-full.mp4" type="video/mp4">Your browser does not support embedded video. Visit the SUN / Kuafu project website to view it.</video><p id="full-video-caption">Complete original project video, from program-guided manipulation in simulation to physical robot deployment. Audio is available through the player controls.</p></section>

<div class="case-body"><div class="case-main">
<section><h2>The problem</h2><p>A multi-stage manipulation task has to mean the same thing to a planner, a reward function, and a learned policy. Rewriting its objectives at each step can lose the geometric relationships that make a task succeed.</p><p>SUN Programs retain those relationships as typed executable task specifications. The same specification produces optimal-control objectives, satisfaction predicates, and learning rewards. Kuafu equips a foundation-model agent with the tools to form, verify, repair, and learn from these programs.</p></section>
<section><h2>What I built</h2><ul><li><strong>The Kuafu harness:</strong> an agentic workflow that connects object videos and language instructions to stage-based task programs, MPC verification, and policy learning.</li><li><strong>Diagnostic repair and learning:</strong> feedback from closed-loop verification guides program repair; training diagnostics guide reward-weight and correction-strength calibration.</li><li><strong>Demonstration collection:</strong> automated collection with learned controllers, plus a web-based human-teleoperation application using AgileX PIKA task-space controls in simulation.</li><li><strong>Visual-policy learning and deployment:</strong> RGB, point-cloud, and multi-task VLA training on generated data; a DP3 pipeline for zero-shot deployment on Franka FR3 and Kinova Gen3.</li></ul><p>This is collaborative research. I am a co-first author with Zhi Li; the contributions above describe my work within the team.</p></section>
<section><h2>How the system fits together</h2><div class="process"><div><span>01</span><h3>Specify</h3><p>Ground task stages in geometric relations.</p></div><div><span>02</span><h3>Verify</h3><p>Use MPC feedback to repair task programs.</p></div><div><span>03</span><h3>Learn</h3><p>Combine behavior cloning and bounded residual RL.</p></div><div><span>04</span><h3>Deploy</h3><p>Train visual policies on generated demonstrations.</p></div></div><figure><img src="../assets/pipeline1.png" loading="lazy" alt="Original Kuafu method diagram, showing program formation, MPC verification, behavior cloning, residual learning, and deployment"><figcaption>The original method figure from the SUN manuscript.</figcaption></figure></section>
<section><h2>Results, with their evaluation scope</h2><table class="result-table"><caption>Reported results from the current SUN manuscript.</caption><thead><tr><th scope="col">Result</th><th scope="col">What was measured</th></tr></thead><tbody><tr><td>95.6%</td><td>Final program formation-and-verification success: 43 of 45 independent runs, including diagnostic repair.</td></tr><tr><td>82.03%</td><td>Task-macro success of the primary privileged controller across nine simulated manipulation tasks. The reported three-run mean is 79.43%.</td></tr><tr><td>10.57×</td><td>Successful demonstration throughput relative to human teleoperation, after controller training. Including controller preparation, mean break-even is 35 demonstrations for cost and 513 for time.</td></tr><tr><td>46.02%</td><td>DP3 mean success on nine simulated tasks with 500 successful demonstrations per task; SkillGen with the same learner achieves 22.44%, a 23.6 percentage-point gap after rounding.</td></tr><tr><td>34.0%</td><td>Physical deployment success over 106 trials, across six tasks and three robot–gripper configurations. DP3 is trained on 1,000 simulated trajectories per task.</td></tr></tbody></table><div class="result-note"><p>Simulation and hardware results measure different settings. Physical deployment uses no real-world demonstrations or fine-tuning; the 82.03% simulation result is not a hardware success rate.</p></div></section>
<section id="hardware"><h2>On physical hardware</h2><p>A Franka FR3 opens a drawer and places a cube inside using a policy trained in simulation. This excerpt retains the original demonstration’s 5× playback speed.</p><figure><video controls controlslist="nodownload" playsinline preload="none" poster="../assets/franka-hardware.jpg" aria-label="Franka FR3 drawer manipulation demonstration at five times speed"><source src="../assets/franka-demo.mp4" type="video/mp4">Your browser does not support HTML video. <a href="https://kuafu-robo.github.io/#video">View it on the SUN / Kuafu project website.</a></video><figcaption>Silent excerpt from the original SUN / Kuafu project video. <a href="https://kuafu-robo.github.io/#video" target="_blank" rel="noopener noreferrer">Watch the complete project video ↗</a></figcaption></figure></section>
<section><h2>Turning controllers into data</h2><p>The learned controllers also act as demonstration generators for downstream visual policies. The throughput advantage is measured after controller training; the break-even analysis accounts for preparation time.</p><figure><img src="../assets/sun_throughput.png" loading="lazy" alt="Per-task successful demonstration throughput comparing Kuafu, human teleoperation, and data-generation baselines"><figcaption>Successful demonstration throughput for the nine-task benchmark.</figcaption></figure><figure><img src="../assets/sun_breakeven.png" loading="lazy" alt="Per-task time break-even curves including controller training"><figcaption>Time break-even including controller preparation.</figcaption></figure></section>
</div><aside class="case-sidebar" aria-label="Project summary"><div><p class="mono">MY CONTRIBUTION</p><p>Harness development, program verification and repair, learning and data collection, visual-policy training, and hardware deployment.</p></div><div><p class="mono">ROBOTICS SKILLS</p><ul class="tags"><li>Robotic manipulation</li><li>Reinforcement learning</li><li>Imitation learning</li><li>Model predictive control</li><li>Visuomotor learning</li><li>Sim-to-real transfer</li><li>Teleoperation</li></ul></div><div><p class="mono">STATUS</p><p>Under review, 2026.<br>Co-first-authored research at UCLA.</p></div></aside></div>
<div class="case-footer"><a class="text-link" href="../#work">← All selected work</a><a class="text-link" href="coactivity.html">Next: Human–robot co-activity ↗</a></div></div>'''

COACTIVITY = '''
<div class="container"><header class="case-header"><a class="back-link" href="../#work">← Back to selected work</a><p class="eyebrow">PLANNING + HUMAN–ROBOT INTERACTION / ICRA 2023</p><h1>Rearrange Indoor Scenes<br><span>for Human–Robot Co-Activity</span></h1><p class="case-lead">Rearrange Indoor Scenes for Human–Robot Co-Activity. An optimization-based framework that makes indoor spaces more accessible to robots while preserving the furniture relationships that support human activities.</p><div class="case-meta"><span>Co-first author</span><span>IEEE ICRA · 2023</span><span>UCLA</span></div><div class="case-links"><a class="button primary" href="https://arxiv.org/abs/2303.05676" target="_blank" rel="noopener noreferrer">Read the paper ↗</a><a class="text-link" href="https://github.com/Rayckey/scene_coactivity" target="_blank" rel="noopener noreferrer">Source code ↗</a><a class="text-link" href="https://sites.google.com/view/coactivity" target="_blank" rel="noopener noreferrer">Project website ↗</a></div></header>
<figure class="case-media"><video controls muted loop playsinline preload="none" poster="../assets/coactivity.jpg" aria-label="Rotating visualization of an optimized simulated living room"><source src="../assets/coactivity.mp4" type="video/mp4">Your browser does not support HTML video. <a href="../assets/coactivity.mp4">Download the visualization.</a></video><figcaption>An optimized living room, visualized in simulation. Original animation from the project repository.</figcaption></figure>
<div class="case-body"><div class="case-main">
<section><h2>The problem</h2><p>A room that works for a person may be difficult for a mobile manipulator to navigate. A robot’s footprint can make a narrow passage impassable, and its reach can make an otherwise visible object inaccessible.</p><p>This work changes the scene layout itself. It rearranges furniture to improve robot access while retaining functional relationships—such as a chair’s relationship to a desk—that make a room useful to people.</p></section>
<section><h2>My contribution</h2><p>I led development of the scene-rearrangement system and implemented hierarchical optimization using adaptive simulated annealing (ASA) and covariance matrix adaptation evolution strategy (CMA-ES).</p><p>The optimization combines robot footprint and reachability models with learned spatial relationships, ConceptNet semantics, and functional object groups. I am a co-first author with Zihang Zhao and Ziyuan Jiao.</p></section>
<section><h2>Balancing two kinds of access</h2><div class="process"><div><span>01</span><h3>Model the room</h3><p>Represent objects and their functional relations.</p></div><div><span>02</span><h3>Model the robot</h3><p>Account for its footprint and reachability.</p></div><div><span>03</span><h3>Optimize</h3><p>Reposition functional groups and refine the layout.</p></div><div><span>04</span><h3>Evaluate</h3><p>Measure access and assess layout quality.</p></div></div><p>Spatial co-occurrence is learned from SUNCG, with semantic relationships from ConceptNet. The objective balances navigable space and reachable objects against the human preferences represented by these relationships.</p></section>
<section><h2>Results</h2><table class="result-table"><caption>Average improvements reported in the published SUNCG scene evaluation.</caption><thead><tr><th scope="col">Improvement</th><th scope="col">Measure</th></tr></thead><tbody><tr><td>+14%</td><td>Accessible space for the robot.</td></tr><tr><td>+30%</td><td>Objects the robot can reach and interact with.</td></tr></tbody></table><p>A human study also assessed the quality of the rearranged scenes. These results come from the paper’s scene evaluation; they are not a physical robot task-completion rate.</p></section>
<section><h2>Why it matters</h2><p>Planning depends on both the robot and its environment. Explicitly representing the robot’s embodiment lets us ask a complementary question: how should a space change so that a robot can work alongside people?</p><p>This project is part of my broader work on embodiment-aware task realization, alongside mobile manipulation, tool-use planning, and robot learning.</p></section>
<section><h2>Publication</h2><p><strong>Weiqi Wang*</strong>, Zihang Zhao*, Ziyuan Jiao*, Yixin Zhu, Song-Chun Zhu, and Hangxin Liu. “Rearrange Indoor Scenes for Human–Robot Co-Activity.” IEEE International Conference on Robotics and Automation (ICRA), 2023, pp. 11943–11949. *Equal contribution.</p><p><a href="https://arxiv.org/abs/2303.05676" target="_blank" rel="noopener noreferrer">Read on arXiv</a> · <a href="https://github.com/Rayckey/scene_coactivity" target="_blank" rel="noopener noreferrer">Explore the implementation</a></p></section>
</div><aside class="case-sidebar" aria-label="Project summary"><div><p class="mono">MY CONTRIBUTION</p><p>System development, hierarchical optimization, robot footprint and reachability integration, and semantic scene modeling.</p></div><div><p class="mono">ROBOTICS SKILLS</p><ul class="tags"><li>Robot navigation</li><li>Numerical optimization</li><li>Reachability analysis</li><li>Human–robot interaction</li><li>Computational geometry</li></ul></div><div><p class="mono">PUBLICATION</p><p>IEEE ICRA, 2023.<br>Co-first-authored research.</p></div></aside></div><div class="case-footer"><a class="text-link" href="sun.html">← SUN / Kuafu</a><a class="text-link" href="../#work">All selected work ↗</a></div></div>'''

if __name__ == '__main__':
    # Keep the homepage and case studies on the same stylesheet revision.
    home = PUBLIC / 'index.html'
    html = home.read_text()
    for path in ('styles.css', 'assets/favicon.svg'):
        html = re.sub(rf'href="{re.escape(path)}(?:\?v=[^"]*)?"',
                      f'href="{asset_url(path)}"', html)
    home.write_text(html)
    folder = PUBLIC / 'projects'
    folder.mkdir(exist_ok=True)
    for slug, title, desc, content in [
        ('sun', 'SUN / Kuafu', 'Weiqi Wang’s work on agentic robot learning, persistent task programs, MPC verification, residual RL, and sim-to-real deployment.', SUN),
        ('coactivity', 'Human–Robot Co-Activity', 'Weiqi Wang’s ICRA 2023 research on optimizing indoor scenes for robot access while preserving human activities.', COACTIVITY),
    ]:
        (folder / f'{slug}.html').write_text(page(title, desc, content))
        print(f'Built projects/{slug}.html')
